apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: sanderwieringa.azurecr.io/react-app:latest
          resources:
            requests:
              cpu: "2" # Requesting 0.5 CPU units
            limits:
              cpu: "4"   # Limiting to 1 CPU unit
          ports:
            - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: react-app-loadbalancer
spec:
  selector:
    app: react-app-loadbalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
