name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY_SERVER: sanderwieringa.azurecr.io
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_PASSWORD }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  K8S_NAMESPACE: default
  K8S_CLUSTER: 9Gag-Backend
  K8S_MANIFEST_PATH: kubernetes/deployment.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the container registry
        run: |
          docker login $REGISTRY_SERVER -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD

      - name: Build and push Docker image
        run: |
          docker buildx build --push --progress plain \
            --tag $REGISTRY_SERVER/react-app:latest \
            --file path/to/your/Dockerfile .

      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az extension add --name azure-cli-extensions
            az extension add --name k8s-extension

      - name: Set up AKS cluster
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: $K8S_MANIFEST_PATH
          namespace: $K8S_NAMESPACE
          images: $REGISTRY_SERVER/react-app:latest
          imagePullSecrets: ${{ secrets.REGISTRY_SECRET }}
          aksCluster: $K8S_CLUSTER
