name: Build and Deploy React App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: react-app
  REGISTRY_NAME: sanderwieringa
  AKS_RESOURCE_GROUP: 9Gag-Backend
  AKS_CLUSTER_NAME: 9Gag-Backend
  AKS_NAMESPACE: default
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  LOGIN_SERVER: sanderwieringa.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

#       - name: Build and Test
#         run: |
#           npm ci
#           npm run build
#           npm test --if-present




      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      
#       - name: Authenticate Kubernetes container registry
#         uses: Azure/k8s-set-context@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#           containerRegistry: ${{ env.LOGIN_SERVER }}
#           containerRegistryUsername: ${{ secrets.REGISTRY_USERNAME }}
#           containerRegistryPassword: ${{ secrets.REGISTRY_PASSWORD }}



      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx build --push --tag ${{ env.LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/react-app .
          docker buildx imagetools inspect ${{ env.LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/react-app




#       - name: Build Docker image
#         run: |
#           docker build . -t ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
#           docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
#           docker push ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          
          
          

#       - name: Set up Azure CLI
#         uses: azure/CLI@v1

      - name: Set up Azure CLI
        run: |
           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
           
           
           
#       - name: Deploy to AKS
#         uses: azure/aks-set-context@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#           cluster-name: ${{ env.AKS_CLUSTER_NAME }}
#           resource-group: ${{ env.AKS_RESOURCE_GROUP }}

#       - name: Deploy to AKS
#         run: |
#           az acr login --name ${{ env.REGISTRY_NAME }}

#           kubectl apply -f kubernetes/deployment.yaml -n ${{ env.AKS_NAMESPACE }}



      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure AKS credentials
        run: az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: kubectl apply -f kubernetes/deployment.yaml -n ${{ env.AKS_NAMESPACE }}
